name: "Terraform detect OS type"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  detect-os-job:
    runs-on: ubuntu-latest

    name: A job to test OS type on remote runner
    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.TERRAFORM_RSA }}

        # Initialize a new or existing Terraform working directory by creating initial files, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Detecting OS
        run: terraform apply --auto-approve

      - name: Trigger First Responder
        run: |
          curl \
          -X POST \
          -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/marcmodin/project-docs-repo/dispatches \
          --data '{"event_type": "build_application"}'
